#!/usr/bin/env bash

DIRS=(
	"$HOME/Projects/apps"
	"$HOME/Projects/elixir"
	"$HOME/Documents/Brain2.0"
	"$HOME/Documents/files"
	"$HOME/Documents/mydox"
	"$HOME/Documents"
	"$HOME/Pictures/screenshots"
	"$HOME/Pictures"
)

tmux_go() {
  local target="$1"

  if [[ -n "$TMUX" ]]; then
    tmux switch-client -t "$target"
  else
    tmux attach -t "$target"
  fi
}

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(fd . "${DIRS[@]}" --type=dir --max-depth=1 --full-path \
		| sed "s|^$HOME/||" \
		| sk --margin 10% --color="bw")
	[[ $selected ]] && selected="$HOME/$selected"
fi

[[ ! $selected ]] && exit 1

selected_name=$(basename "$selected" | tr . _)

# Special case: rws is always built by tmux-rws
if [[ "$selected_name" == "rws" ]]; then
  exec tmux-rws
fi

# Generic sessions
if ! tmux has-session -t "$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux_go "$selected_name"
